---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - tmp/**/*
    - bin/**/*
    - vendor/**/*

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
